//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetSure_Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicyHolder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PolicyHolder()
        {
            this.ph_vp_claim = new HashSet<ph_vp_claim>();
        }
    
        public string policyNumber { get; set; }
        public string policyHolder1 { get; set; }
        public string insurer { get; set; }
        public string phAddress { get; set; }
        public string phSurburb { get; set; }
        public int phPostCode { get; set; }
        public string phState { get; set; }
        public string phPhone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ph_vp_claim> ph_vp_claim { get; set; }
    }
}
