//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetSure_Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VethubClaim
    {
        public int policyNumber { get; set; }
        public string policyHolder { get; set; }
        public string petName { get; set; }
        public string vetPractice { get; set; }
        public decimal amount { get; set; }
        public string microChip { get; set; }
        public int vetHubRef { get; set; }
        public int claimRef { get; set; }
        public int claim { get; set; }
        public string status { get; set; }
        public System.DateTime dateSubmitted { get; set; }
    }
}
