//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetSure_Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VetPractise
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VetPractise()
        {
            this.VethubClaims = new HashSet<VethubClaim>();
        }
    
        public int vpId { get; set; }
        public string vetPractise1 { get; set; }
        public string submittedBy { get; set; }
        public string vpAddress { get; set; }
        public string vpSuburb { get; set; }
        public int vpPostCode { get; set; }
        public string vpState { get; set; }
        public string vpPhone { get; set; }
        public string vpEmail { get; set; }
        public string VPMS_Version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VethubClaim> VethubClaims { get; set; }
    }
}
